version: "3.9"

services:
  backend:
    build: ./backend
    container_name: cringe-volume-backend
    env_file:
      - .env
    environment:
      # внутри контейнера music лежит в /app/music
      MUSIC_DIR: /app/music
      # self-webhook через localhost (внутри контейнера)
      PAYMENT_CALLBACK_INTERNAL_URL: http://localhost:${SERVER_PORT:-8080}/api/payments/webhook
    volumes:
      - music:/app/music
    networks:
      - remnawave-network

volumes:
  music:

networks:
  remnawave-network:
    name: remnawave-network
    external: true
