version: "3.9"

services:
  backend:
    build: ./backend
    container_name: cringe-volume-backend
    env_file:
      - .env
    volumes:
      - music:/app/music
    networks:
      - remnawave-network

volumes:
  music:

networks:
  remnawave-network:
    name: remnawave-network
    external: true
